/**
 * Codegen: symbols/batch001/{symbols.json,symbols.svg}
 *   → src/assets/symbol-manifest.ts  (metadata — consumed by the generator)
 *   → src/assets/batch001.ts         (markup   — consumed by the renderer)
 *
 * Run: npx tsx scripts/extract-glyphs.ts
 * The outputs are committed; tests/extract-glyphs.test.ts pins idempotency.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

export interface SymbolMeta {
  cls: 'fixed' | 'mark' | 'canopy' | 'pattern';
  viewBox: [number, number, number, number];
  footprint: [number, number] | null;
  anchor: [number, number];
  rotation: 'invariant' | 'free' | 'locked' | 'snap-cardinal';
  zBand: 'ground' | 'parcel' | 'route' | 'structure' | 'canopy' | 'overlay';
  minScale: number;
  scaleTo?: string;
  tags: string[];
}

/** Sprite → id → inner markup of its <symbol>, per-file <style> blocks dropped. */
export function parseSprite(svg: string): Map<string, string> {
  const out = new Map<string, string>();
  const re = /<symbol id="([^"]+)"[^>]*>([\s\S]*?)<\/symbol>/g;
  let m: RegExpExecArray | null;
  while ((m = re.exec(svg)) !== null) {
    const inner = m[2].replace(/<style>[\s\S]*?<\/style>/g, '').trim();
    out.set(m[1], inner);
  }
  return out;
}

export function buildManifest(json: {
  symbols: Record<string, Record<string, unknown>>;
}): Record<string, SymbolMeta> {
  const out: Record<string, SymbolMeta> = {};
  for (const [id, s] of Object.entries(json.symbols)) {
    out[id] = {
      cls: s.cls as SymbolMeta['cls'],
      viewBox: s.viewBox as SymbolMeta['viewBox'],
      footprint: (s.footprint ?? null) as SymbolMeta['footprint'],
      anchor: s.anchor as SymbolMeta['anchor'],
      rotation: s.rotation as SymbolMeta['rotation'],
      zBand: s.zBand as SymbolMeta['zBand'],
      minScale: s.minScale as number,
      ...(s.scaleTo !== undefined ? { scaleTo: s.scaleTo as string } : {}),
      tags: (s.tags ?? []) as string[],
    };
  }
  return out;
}

const GEN_HEADER = '// GENERATED by scripts/extract-glyphs.ts — do not edit by hand.\n' +
  '// Regenerate: npx tsx scripts/extract-glyphs.ts\n';

export function renderManifestModule(manifest: Record<string, SymbolMeta>): string {
  return `${GEN_HEADER}
export type SymbolClass = 'fixed' | 'mark' | 'canopy' | 'pattern';
export type SymbolSheetZBand = 'ground' | 'parcel' | 'route' | 'structure' | 'canopy' | 'overlay';
export interface SymbolMeta {
  cls: SymbolClass;
  viewBox: [number, number, number, number];
  footprint: [number, number] | null;
  anchor: [number, number];
  rotation: 'invariant' | 'free' | 'locked' | 'snap-cardinal';
  zBand: SymbolSheetZBand;
  minScale: number;
  scaleTo?: string;
  tags: string[];
}

export const SYMBOL_MANIFEST: Record<string, SymbolMeta> = ${JSON.stringify(manifest, null, 2)};
`;
}

export function renderGlyphModule(
  manifest: Record<string, SymbolMeta>,
  sprite: Map<string, string>,
): string {
  const entries: Record<string, { body: string; sil: string }> = {};
  for (const id of Object.keys(manifest)) {
    const body = sprite.get(id);
    const sil = sprite.get(`${id}-sil`);
    if (body === undefined || sil === undefined) {
      throw new Error(`sprite missing body or sil for ${id}`);
    }
    entries[id] = { body, sil };
  }
  return `${GEN_HEADER}//
// Symbol artwork © Barry Gill, licensed CC-BY-4.0 with the Rendered Output
// Exception — see symbols/LICENSE. Attribution is required when
// redistributing this library, waived for rendered map output.

export interface GlyphMarkup { body: string; sil: string }

export const BATCH001_GLYPHS: Record<string, GlyphMarkup> = ${JSON.stringify(entries, null, 2)};
`;
}

function main(): void {
  const root = join(dirname(fileURLToPath(import.meta.url)), '..');
  const batch = join(root, 'symbols', 'batch001');
  const json = JSON.parse(readFileSync(join(batch, 'symbols.json'), 'utf8'));
  const sprite = parseSprite(readFileSync(join(batch, 'symbols.svg'), 'utf8'));
  const manifest = buildManifest(json);
  writeFileSync(join(root, 'src', 'assets', 'symbol-manifest.ts'), renderManifestModule(manifest));
  writeFileSync(join(root, 'src', 'assets', 'batch001.ts'), renderGlyphModule(manifest, sprite));
  console.log(`wrote ${Object.keys(manifest).length} symbols`);
}

if (process.argv[1] && process.argv[1].endsWith('extract-glyphs.ts')) main();
