/**
 * Codegen: symbols/refined/{symbols.json,symbols.svg,symbols-biomes.svg,symbols-parcel.svg}
 *   → src/assets/refined-manifest.ts  (metadata — consumed by src/village/glyphs.ts)
 *   → src/assets/refined-glyphs.ts    (markup   — consumed by src/village/render.ts)
 *
 * Sibling to scripts/extract-glyphs.ts, for the NEW (src/village/) engine's
 * 91-symbol refined set. Does not touch batch001's codegen or outputs.
 *
 * Two differences from the batch001 pipeline, both because the refined set
 * is a bigger, more varied generation:
 *   - three sprites are merged into one id → markup map, not one;
 *   - a missing `-sil` twin is tolerated. Parcel-band assets (greens, field
 *     tiles, field edges — zBand "parcel", ground the generator draws
 *     under buildings) legitimately have none: ground casts no shadow.
 *     Canopy-band assets (zBand "canopy") likewise carry no twin, for the
 *     same reason integration.md gives for both: "a change in the ground
 *     [or foliage], not a thing standing on it". Only `structure`-band ids
 *     are required to carry one — a missing sil there is still an error.
 *
 * Run: npx tsx scripts/extract-refined-glyphs.ts
 * The outputs are committed; tests/extract-refined-glyphs.test.ts pins
 * idempotency, the sil/no-sil split, and typed metadata.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import { parseSprite } from './extract-glyphs.js';

export type RefinedSymbolClass = 'fixed' | 'mark' | 'canopy' | 'pattern';
export type RefinedSymbolZBand = 'ground' | 'parcel' | 'route' | 'structure' | 'canopy' | 'overlay';

export interface RefinedSymbolMeta {
  cls: RefinedSymbolClass;
  viewBox: [number, number, number, number];
  footprint: [number, number] | null;
  anchor: [number, number];
  /**
   * Optional, unlike batch001's manifest: the eight `sm-field-*` pattern
   * tiles carry no "rotation" key at all in symbols.json — a tile is
   * rotated via its `patternTransform`, not by this per-id contract, so
   * there is nothing to record. Every `fixed` and `canopy` id does carry one.
   */
  rotation?: 'invariant' | 'free' | 'locked' | 'snap-cardinal';
  zBand: RefinedSymbolZBand;
  minScale: number;
  tags: string[];
}

/** Merge every <symbol> across all three sprites into one id → markup map. */
export function mergeSprites(sprites: string[]): Map<string, string> {
  const out = new Map<string, string>();
  for (const svg of sprites) {
    for (const [id, markup] of parseSprite(svg)) out.set(id, markup);
  }
  return out;
}

export function buildRefinedManifest(json: {
  symbols: Record<string, Record<string, unknown>>;
}): Record<string, RefinedSymbolMeta> {
  const out: Record<string, RefinedSymbolMeta> = {};
  for (const [id, s] of Object.entries(json.symbols)) {
    out[id] = {
      cls: s.cls as RefinedSymbolMeta['cls'],
      viewBox: s.viewBox as RefinedSymbolMeta['viewBox'],
      footprint: (s.footprint ?? null) as RefinedSymbolMeta['footprint'],
      anchor: s.anchor as RefinedSymbolMeta['anchor'],
      ...(s.rotation !== undefined
        ? { rotation: s.rotation as RefinedSymbolMeta['rotation'] }
        : {}),
      zBand: s.zBand as RefinedSymbolMeta['zBand'],
      minScale: s.minScale as number,
      tags: (s.tags ?? []) as string[],
    };
  }
  return out;
}

const GEN_HEADER = '// GENERATED by scripts/extract-refined-glyphs.ts — do not edit by hand.\n'
  + '// Regenerate: npx tsx scripts/extract-refined-glyphs.ts\n';

export function renderRefinedManifestModule(manifest: Record<string, RefinedSymbolMeta>): string {
  return `${GEN_HEADER}
export type RefinedSymbolClass = 'fixed' | 'mark' | 'canopy' | 'pattern';
export type RefinedSymbolZBand = 'ground' | 'parcel' | 'route' | 'structure' | 'canopy' | 'overlay';
export interface RefinedSymbolMeta {
  cls: RefinedSymbolClass;
  viewBox: [number, number, number, number];
  footprint: [number, number] | null;
  anchor: [number, number];
  rotation?: 'invariant' | 'free' | 'locked' | 'snap-cardinal';
  zBand: RefinedSymbolZBand;
  minScale: number;
  tags: string[];
}

export const REFINED_MANIFEST: Record<string, RefinedSymbolMeta> = ${JSON.stringify(manifest, null, 2)};
`;
}

export interface RefinedGlyphMarkup {
  body: string;
  /**
   * Absent, not an empty string, for parcel- and canopy-band ids: ground
   * and vegetation cast no shadow (integration.md's shadow contract), so
   * there is no silhouette twin to draw and fabricating an empty one would
   * let a caller paint an invisible shadow instead of skipping it outright.
   */
  sil?: string;
}

export function renderRefinedGlyphModule(
  manifest: Record<string, RefinedSymbolMeta>,
  sprite: Map<string, string>,
): string {
  const entries: Record<string, RefinedGlyphMarkup> = {};
  for (const [id, meta] of Object.entries(manifest)) {
    const body = sprite.get(id);
    if (body === undefined) {
      throw new Error(`sprite missing body for ${id}`);
    }
    const sil = sprite.get(`${id}-sil`);
    if (sil === undefined && meta.zBand === 'structure') {
      throw new Error(`structure-band id ${id} is missing its required -sil twin`);
    }
    entries[id] = sil !== undefined ? { body, sil } : { body };
  }
  return `${GEN_HEADER}//
// Symbol artwork © Barry Gill, licensed CC-BY-4.0 with the Rendered Output
// Exception — see symbols/LICENSE. Attribution is required when
// redistributing this library, waived for rendered map output.

export interface RefinedGlyphMarkup { body: string; sil?: string }

export const REFINED_GLYPHS: Record<string, RefinedGlyphMarkup> = ${JSON.stringify(entries, null, 2)};
`;
}

function main(): void {
  const root = join(dirname(fileURLToPath(import.meta.url)), '..');
  const refined = join(root, 'symbols', 'refined');
  const json = JSON.parse(readFileSync(join(refined, 'symbols.json'), 'utf8'));
  const sprite = mergeSprites([
    readFileSync(join(refined, 'symbols.svg'), 'utf8'),
    readFileSync(join(refined, 'symbols-biomes.svg'), 'utf8'),
    readFileSync(join(refined, 'symbols-parcel.svg'), 'utf8'),
  ]);
  const manifest = buildRefinedManifest(json);
  writeFileSync(join(root, 'src', 'assets', 'refined-manifest.ts'), renderRefinedManifestModule(manifest));
  writeFileSync(join(root, 'src', 'assets', 'refined-glyphs.ts'), renderRefinedGlyphModule(manifest, sprite));
  console.log(`wrote ${Object.keys(manifest).length} symbols`);
}

if (process.argv[1] && process.argv[1].endsWith('extract-refined-glyphs.ts')) main();
