import { writeFileSync } from 'node:fs';
import sharp from 'sharp';
import { REFINED_GLYPHS } from '../src/assets/refined-glyphs.js';
import { REFINED_MANIFEST } from '../src/assets/refined-manifest.js';
import { refinedStyle } from '../src/assets/refined-style.js';

// Measure artwork, not manifest metre footprints. Eight samples per art unit,
// plus a half-unit guard on each side for antialiasing and transform rounding.
// Regenerate after artwork changes: npm run measure:city-glyphs
async function main() {
  const rows: string[] = [];
  for (const [id, glyph] of Object.entries(REFINED_GLYPHS)) {
    const meta = REFINED_MANIFEST[id];
    if (meta.zBand !== 'structure' || meta.cls !== 'fixed') continue;
    const svg = `<svg xmlns="http://www.w3.org/2000/svg" width="512" height="512" viewBox="0 0 64 64"><style>${refinedStyle()}</style>${glyph.body}${glyph.sil ?? ''}</svg>`;
    const { data, info } = await sharp(Buffer.from(svg)).ensureAlpha().raw().toBuffer({ resolveWithObject: true });
    let x0 = info.width, y0 = info.height, x1 = 0, y1 = 0, area = 0;
    for (let y = 0; y < info.height; y++) for (let x = 0; x < info.width; x++) {
      const alpha = data[(y * info.width + x) * 4 + 3];
      area += alpha / 255 / 64;
      if (!alpha) continue;
      x0 = Math.min(x0, x); y0 = Math.min(y0, y);
      x1 = Math.max(x1, x + 1); y1 = Math.max(y1, y + 1);
    }
    const bounds = [x0 / 8 - 0.5, y0 / 8 - 0.5, x1 / 8 + 0.5, y1 / 8 + 0.5];
    rows.push(`  '${id}': { bounds: [${bounds.join(', ')}], area: ${area.toFixed(2)} },`);
  }
  writeFileSync('src/assets/refined-ink.ts', `// GENERATED by scripts/measure-city-glyphs.ts. Bounds include a 0.5 art-unit guard.\n// Area is a raster estimate of the body/silhouette union, not housing capacity.\nexport const REFINED_INK: Record<string, { bounds: [number, number, number, number]; area: number }> = {\n${rows.join('\n')}\n};\n`);
}
void main();
